### PR TITLE
Add templating error handling

### LINKED ISSUE #231: Improve error reporting for environment with invalid Jinja
I've got this error and it turns out there was a generated secret containing `{#`. It would be nice if the error message would be more specific on the template having the syntax error.

```
ERROR: TemplateSyntaxError('Missing end of comment tag')
This /might/ be a batou bug. Please consider reporting it.

      Host: xxx
 Component: yyy

Traceback (simplified, most recent call last):
  File "/xxx/.appenv/127fb75b/lib/python3.8/site-packages/batou/template.py", line 70, in expand
    tmpl = self.env.from_string(templatestr)
  File "/xxx/.appenv/127fb75b/lib/python3.8/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/xxx/.appenv/127fb75b/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/xxx/.appenv/127fb75b/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 7, in template

```

### PR DESCRIPTION
**Pull request by elikoga**
Closes #231

### CODE REVIEW

**Comment by ctheune** [comment]
@elikoga looks good in general. could you post an example of the message we'd see now?

I think one of the things @zagy is looking for is that he can see which template and what code in the template was the reason for the error. I'm not sure whether this is happening here or not.

**Comment by elikoga** [comment]
With
```
[component:hello]
arg = {{#asd}}
```

giving us
```
=================================================== Preparing ====================================================
main: Loading environment `tutorial`...
main: Verifying repository ...
main: Loading secrets ...
=================================== Connecting hosts and configuring model ... ===================================
localhost: Connecting via local (1/1)


ERROR: An error occured while rendering a template: unexpected char '#' at 2
  line 1
    {{#asd}}

ERROR: 1 remaining unconfigured component(s): hello
======================================== 2 ERRORS - CONFIGURATION FAILED =========================================
======================================= DEPLOYMENT FAILED (during connect) =======================================
```

Not sure why jinja wants to swallow the additional information, but there it is

**Comment by elikoga** [comment]
...I'm adding a field for the current and root component

**Comment by ctheune** [comment]
That looks great. Do we have a chance to add the template name?

**Comment by ctheune** [comment]
Also, the 3.6 test failed ...

**Comment by elikoga** [comment]
```python
from batou.component import Component
from batou.lib.file import File


class Hello(Component):
    def configure(self):
        self += File("hello", content="Hello world")
        self.template("hello.jinja2")
```
together with
`{#` in the file gives us:

```
============================================ Preparing ============================================
main: Loading environment `tutorial`...
main: Verifying repository ...
main: Loading secrets ...
=========================== Connecting hosts and configuring model ... ============================
localhost: Connecting via local (1/1)


ERROR: An error occured while rendering a template (hello.jinja2): Missing end of comment tag
  line 1
    {#

ERROR: 1 remaining unconfigured component(s): hello
================================= 2 ERRORS - CONFIGURATION FAILED =================================
=============================== DEPLOYMENT FAILED (during connect) ================================
```

as wanted

**Comment by elikoga** [comment]
1. I made the exception be wrapped by a `UnknownComponentConfigurationError` again, see #428

**Review by ctheune — DISMISSED** [review]

**Comment by ctheune** [comment]
Looks like we need a rebase, though.

**Review by zagy — DISMISSED** [review]

**Pull request merged**
