### PR TITLE
Listen to the Twitter gods

### PR DESCRIPTION
**Pull request by jugmac00**
modified:   .github/workflows/main.yml

### CODE REVIEW

**Comment by ctheune** [comment]
Sure? The unit tests are saying the twitter gods might be wrong ... -_-

**Comment by jugmac00** [comment]
One more try :-D

Unfortunately, the GH Actions do not run in my repo - so I had to create a PR.. .there is much to learn ...

Converted this to a draft - sorry for the noise.

**Comment by jugmac00** [comment]
Kaum macht mans richtig schon gehts.

Test failure comes from the rocket chat hook - unrelated to the git related tests :tada:

**Comment by ctheune** [comment]
bazinga!

**Pull request merged**
