### PR TITLE
Repair `File(group=)`, it now works just like `File(owner=)`

### PR DESCRIPTION
**Pull request by wosc**

### CODE REVIEW

**Comment by icemac** [comment]
@ctheune Tests are failing because of a broken RocketChat integration. Are you going to fix it or should the notification be removed from the CI configuration?

**Comment by ctheune** [comment]
@icemac the failing test is weird/stupid. the notification works when we commit things directly to the repo, but as it uses a secret it isn't available for pull requests. i'm trying to figure out how to make this not fail ...

**Comment by jugmac00** [comment]
You could deposit the secret in the settings of this repository and hope
- you do not misconfigure it
- there is currently no known vulnarability with GH actions :-|

So, probably don't :-)
( https://www.youtube.com/watch?v=_fpXyS_i1xE&ab_channel=anthonywritescode )

**Comment by ctheune** [comment]
That's not the problem. The secret is stored in the repo but doesn't seem to be available to PRs.

**Comment by jugmac00** [comment]
Right, you could make it available to pull requests via the `pull_request_target` workflow, and then you are doomed. That is what the video is about, and oh, how github totally failed to react properly to this vuln.

**Pull request merged**
