### PR TITLE
Point metadata URL to repos

### PR DESCRIPTION
**Pull request by icemac**
instead of private bug tracker

### CODE REVIEW

**Comment by icemac** [comment]
Ups, source repo deleted. But it should not be that hard to reconstruct the PR directly on the 1.x branch to get a better link in PyPI to the code of this project.

**Comment by ctheune** [comment]
lol, yeah, thanks :)

**Comment by ctheune** [comment]
The PR was even still active and could be merged. Please remember to prefer PRs to master ... :)

**Comment by icemac** [comment]
`master` has already a better URL pointing to the documentation from where it is possible to get here via a linkt to Bitbucket.

**Pull request merged**
