### PR TITLE
Update supervisor to 4.x (so it supports Python 3)

### PR DESCRIPTION
**Pull request by wosc**

### CODE REVIEW

**Comment by zagy** [comment]
@wosc were you using this with Batou 1.x?

**Comment by wosc** [comment]
@zagy Nope, we haven't used this yet.

**Comment by zagy** [comment]
Sorry, my question was misleading. Do you expect this to be in batou 1.x? The PR is against master, and that's 2.0 (beta-not-yet-working). But I'll happily also merge it to 1.x.

**Comment by wosc** [comment]
Ah right. :) I personally would be fine with this (only) going to 2.x, because my main reason for wanting to upgrade supervisor is py3 compatibility, which batou-1.x doesn't have anyway.

**Comment by wosc** [comment]
Hi! Any news...?

**Comment by zagy** [comment]
Ah, sorry. On mater (e.g. batou 2) supervisor is already updated. I _think_ this PR can be closed. But maybe I miss something.

**Comment by wosc** [comment]
Ah, yup there's equivalent code on master already, I missed that. Thanks, then we're done here. :)

**Pull request closed without merging**
