### PR TITLE
Limit threadpool

### PR DESCRIPTION
**Pull request by rdrongow**

### CODE REVIEW

**Comment by rdrongow** [comment]
All right. Now hopefully this works now. Did you see my question about types in the environment. It's all fine for me but I'd be happy to change it, if there is sth.

**Comment by rdrongow** [comment]
@ctheune: Would you merge? This would be great and we could use it right away.

**Comment by ctheune** [comment]
Happy to merge, but please notice that due to my major restructuring, batou 2 on master is currently broken. Please don't hurt me ... /o\

**Comment by rdrongow** [comment]
Oh noes! Is there sth. we can do to help?

**Comment by ctheune** [comment]
I'm trying to get things back in order this afternoon, so hopefully you can start using it soon again.

**Pull request merged**
