### PR TITLE
Add ``BATOU_SSH_COMMAND`` environment variable to control SSH invocation

### PR DESCRIPTION
**Pull request by zagy**

### CODE REVIEW

**Comment by zagy** [comment]
This PR closes #17

**Comment by frlan** [comment]
LGTM

**Comment by ctheune** [comment]
So, @zagy said in the issue that we don't need this anymore. Is anyone else interested in this or should I drop this?

**Comment by ctheune** [comment]
Seems like nobody is interested. I'm putting this away for now.

**Pull request closed without merging**
